const DISPATCH_INVENTORY_START = 'DISPATCH_INVENTORY_START';
const DISPATCH_INVENTORY_SUCCESS = 'DISPATCH_INVENTORY_SUCCESS';
const DISPATCH_INVENTORY_FAILURE = 'DISPATCH_INVENTORY_FAILURE';

// STATUS PARA LA TABLA
const FETCH_INVENTORY_START = 'FETCH_INVENTORY_START';
const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS';
const FETCH_INVENTORY_FAILURE = 'FETCH_INVENTORY_FAILURE';

// OTROS TIPOS
const ISOLATE_PART_IN_TABLE = 'ISOLATE_PART_IN_TABLE';
const OPEN_OVERVIEW = 'OPEN_OVERVIEW';
const CLOSE_OVERVIEW = 'CLOSE_OVERVIEW';
const SEARCH_IN_TABLE = 'SEARCH_IN_TABLE';
const STEP_LOADER = 'STEP_LOADER';

const SET_TABLE = 'SET_TABLE';
const SET_STOCK = 'SET_STOCK';
const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
const UPDATE_PRIORITY = 'UPDATE_PRIORITY';

const FILTER_REWORK = "FILTER_REWORK";
const FILTER_CATEGORY = "FILTER_CATEGORY";
const FILTER_PRIORITY = "FILTER_PRIORITY";
const FILTER_STATUS = "FILTER_STATUS";

export default {
  DISPATCH_INVENTORY_START,
  DISPATCH_INVENTORY_SUCCESS,
  DISPATCH_INVENTORY_FAILURE,
  FETCH_INVENTORY_START,
  FETCH_INVENTORY_SUCCESS,
  FETCH_INVENTORY_FAILURE,
  ISOLATE_PART_IN_TABLE,
  OPEN_OVERVIEW,
  CLOSE_OVERVIEW,
  SEARCH_IN_TABLE,
  STEP_LOADER,
  SET_TABLE,
  SET_STOCK,
  UPDATE_CATEGORY,
  UPDATE_PRIORITY,
  FILTER_REWORK,
  FILTER_CATEGORY,
  FILTER_PRIORITY,
  FILTER_STATUS
};
