
const DISPATCH_INVENTORY_START = 'DISPATCH_INVENTORY_START';
const DISPATCH_INVENTORY_SUCCESS = 'DISPATCH_INVENTORY_SUCCESS';
const DISPATCH_INVENTORY_FAILURE = 'DISPATCH_INVENTORY_FAILURE';

// STATUS PARA LA TABLA
const FETCH_INVENTORY_START = 'FETCH_INVENTORY_START';
const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS';
const FETCH_INVENTORY_FAILURE = 'FETCH_INVENTORY_FAILURE';

// OTROS TIPOS
const ISOLATE_PART_IN_TABLE = 'ISOLATE_PART_IN_TABLE'; // Para aislar una parte en la tabla
const OPEN_UPLOAD_MODAL = 'OPEN_UPLOAD_MODAL'; // Para abrir el modal de subida
const CLOSE_UPLOAD_MODAL = 'CLOSE_UPLOAD_MODAL'; // Para cerrar el modal de subida
const SEARCH_IN_TABLE = 'SEARCH_IN_TABLE'; // Para buscar en la tabla
const SET_TABLE = 'SET_TABLE';
// Exportar como default
export default {
    DISPATCH_INVENTORY_START,
    DISPATCH_INVENTORY_SUCCESS,
    DISPATCH_INVENTORY_FAILURE,
    FETCH_INVENTORY_START,
    FETCH_INVENTORY_SUCCESS,
    FETCH_INVENTORY_FAILURE,
    ISOLATE_PART_IN_TABLE,
    OPEN_UPLOAD_MODAL,
    CLOSE_UPLOAD_MODAL,
    SEARCH_IN_TABLE,
    SET_TABLE
};
